### ISSUE TITLE
Questions about training and the full-checkpoint

### ISSUE THREAD

**Issue by SKSKSK94** [NiFangBaAGe/CoordFill#3]
Hi, thanks for your excellent works. 
I have serveral questions.
1. Is the place2 model that you uploaded ([here](https://uofmacau-my.sharepoint.com/:f:/g/personal/mc05379_umac_mo/Em6_auDrqwhKl34MO9w_AggBBMhI3lWb6pQfUbYqCFQ9ZA?e=xduixN)) trained on places-challenge dataset or places365 standard dataset? 
2. Is it possible to release the full checkpoints (e.g, generator, discriminator and optimizer) of the place2 model, so we can finetune it on custom data? 

Looking forward to your reply. Thanks.

**Comment by NiFangBaAGe** [comment]
Thanks for your interest in our work.
The place2 model is trained on places365 standard dataset. And We only save the parameters of the generator.

**Comment by SKSKSK94** [comment]
Thanks for your reply.
I know that currently only generator parameters are saved.
Do you have plans to share the full checkpoint in addition to the generator parameters?
Thanks.
